/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedTracksUploadRouteImport } from './routes/_authenticated/tracks/upload'
import { Route as AuthenticatedProfileTracksRouteImport } from './routes/_authenticated/profile/tracks'
import { Route as AuthenticatedProfileProfileIdIndexRouteImport } from './routes/_authenticated/profile/$profileId/index'
import { Route as AuthenticatedTracksTrackIdEditRouteImport } from './routes/_authenticated/tracks/$trackId/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTracksUploadRoute =
  AuthenticatedTracksUploadRouteImport.update({
    id: '/tracks/upload',
    path: '/tracks/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileTracksRoute =
  AuthenticatedProfileTracksRouteImport.update({
    id: '/profile/tracks',
    path: '/profile/tracks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileProfileIdIndexRoute =
  AuthenticatedProfileProfileIdIndexRouteImport.update({
    id: '/profile/$profileId/',
    path: '/profile/$profileId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTracksTrackIdEditRoute =
  AuthenticatedTracksTrackIdEditRouteImport.update({
    id: '/tracks/$trackId/edit',
    path: '/tracks/$trackId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/player/': typeof PlayerIndexRoute
  '/profile/tracks': typeof AuthenticatedProfileTracksRoute
  '/tracks/upload': typeof AuthenticatedTracksUploadRoute
  '/tracks/$trackId/edit': typeof AuthenticatedTracksTrackIdEditRoute
  '/profile/$profileId/': typeof AuthenticatedProfileProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/player': typeof PlayerIndexRoute
  '/profile/tracks': typeof AuthenticatedProfileTracksRoute
  '/tracks/upload': typeof AuthenticatedTracksUploadRoute
  '/tracks/$trackId/edit': typeof AuthenticatedTracksTrackIdEditRoute
  '/profile/$profileId': typeof AuthenticatedProfileProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/player/': typeof PlayerIndexRoute
  '/_authenticated/profile/tracks': typeof AuthenticatedProfileTracksRoute
  '/_authenticated/tracks/upload': typeof AuthenticatedTracksUploadRoute
  '/_authenticated/tracks/$trackId/edit': typeof AuthenticatedTracksTrackIdEditRoute
  '/_authenticated/profile/$profileId/': typeof AuthenticatedProfileProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/player/'
    | '/profile/tracks'
    | '/tracks/upload'
    | '/tracks/$trackId/edit'
    | '/profile/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/player'
    | '/profile/tracks'
    | '/tracks/upload'
    | '/tracks/$trackId/edit'
    | '/profile/$profileId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/auth/register'
    | '/player/'
    | '/_authenticated/profile/tracks'
    | '/_authenticated/tracks/upload'
    | '/_authenticated/tracks/$trackId/edit'
    | '/_authenticated/profile/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tracks/upload': {
      id: '/_authenticated/tracks/upload'
      path: '/tracks/upload'
      fullPath: '/tracks/upload'
      preLoaderRoute: typeof AuthenticatedTracksUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/tracks': {
      id: '/_authenticated/profile/tracks'
      path: '/profile/tracks'
      fullPath: '/profile/tracks'
      preLoaderRoute: typeof AuthenticatedProfileTracksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/$profileId/': {
      id: '/_authenticated/profile/$profileId/'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId/'
      preLoaderRoute: typeof AuthenticatedProfileProfileIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracks/$trackId/edit': {
      id: '/_authenticated/tracks/$trackId/edit'
      path: '/tracks/$trackId/edit'
      fullPath: '/tracks/$trackId/edit'
      preLoaderRoute: typeof AuthenticatedTracksTrackIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileTracksRoute: typeof AuthenticatedProfileTracksRoute
  AuthenticatedTracksUploadRoute: typeof AuthenticatedTracksUploadRoute
  AuthenticatedTracksTrackIdEditRoute: typeof AuthenticatedTracksTrackIdEditRoute
  AuthenticatedProfileProfileIdIndexRoute: typeof AuthenticatedProfileProfileIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileTracksRoute: AuthenticatedProfileTracksRoute,
  AuthenticatedTracksUploadRoute: AuthenticatedTracksUploadRoute,
  AuthenticatedTracksTrackIdEditRoute: AuthenticatedTracksTrackIdEditRoute,
  AuthenticatedProfileProfileIdIndexRoute:
    AuthenticatedProfileProfileIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  PlayerIndexRoute: PlayerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
