/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as TracksUploadRouteImport } from './routes/tracks/upload'
import { Route as ProfileTracksRouteImport } from './routes/profile/tracks'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as TracksTrackIdEditRouteImport } from './routes/tracks/$trackId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksUploadRoute = TracksUploadRouteImport.update({
  id: '/tracks/upload',
  path: '/tracks/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTracksRoute = ProfileTracksRouteImport.update({
  id: '/profile/tracks',
  path: '/profile/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksTrackIdEditRoute = TracksTrackIdEditRouteImport.update({
  id: '/tracks/$trackId/edit',
  path: '/tracks/$trackId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/tracks': typeof ProfileTracksRoute
  '/tracks/upload': typeof TracksUploadRoute
  '/player/': typeof PlayerIndexRoute
  '/tracks/$trackId/edit': typeof TracksTrackIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/tracks': typeof ProfileTracksRoute
  '/tracks/upload': typeof TracksUploadRoute
  '/player': typeof PlayerIndexRoute
  '/tracks/$trackId/edit': typeof TracksTrackIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/tracks': typeof ProfileTracksRoute
  '/tracks/upload': typeof TracksUploadRoute
  '/player/': typeof PlayerIndexRoute
  '/tracks/$trackId/edit': typeof TracksTrackIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/profile/tracks'
    | '/tracks/upload'
    | '/player/'
    | '/tracks/$trackId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/profile/tracks'
    | '/tracks/upload'
    | '/player'
    | '/tracks/$trackId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/profile/tracks'
    | '/tracks/upload'
    | '/player/'
    | '/tracks/$trackId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProfileTracksRoute: typeof ProfileTracksRoute
  TracksUploadRoute: typeof TracksUploadRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
  TracksTrackIdEditRoute: typeof TracksTrackIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/upload': {
      id: '/tracks/upload'
      path: '/tracks/upload'
      fullPath: '/tracks/upload'
      preLoaderRoute: typeof TracksUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/tracks': {
      id: '/profile/tracks'
      path: '/profile/tracks'
      fullPath: '/profile/tracks'
      preLoaderRoute: typeof ProfileTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$trackId/edit': {
      id: '/tracks/$trackId/edit'
      path: '/tracks/$trackId/edit'
      fullPath: '/tracks/$trackId/edit'
      preLoaderRoute: typeof TracksTrackIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProfileTracksRoute: ProfileTracksRoute,
  TracksUploadRoute: TracksUploadRoute,
  PlayerIndexRoute: PlayerIndexRoute,
  TracksTrackIdEditRoute: TracksTrackIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
